### ISSUE TITLE
-r segfault in direct mode

### ISSUE THREAD

**Issue by bircoph** [xaionaro/clsync#116]
$ clsync -M direct -W a -D b -r -S cp
Segmentation fault

$ clsync --version
Info: clsync v0.4.36
        Dmitry Yu Okunev <dyokunev@ut.mephi.ru> 0x8E30679C

Compiled with options -DINOTIFY_SUPPORT -DGIO_SUPPORT -DBACKTRACE_SUPPORT -DGETMNTENT_SUPPORT

$ ls -1R
.:
a
b

./a:
file.txt

./b:

Program received signal SIGSEGV, Segmentation fault.
0xb7af5182 in ____strtol_l_internal () from /lib/libc.so.6
(gdb) bt
#0  0xb7af5182 in ____strtol_l_internal () from /lib/libc.so.6
#1  0xb7af4f40 in strtol () from /lib/libc.so.6
#2  0x08050938 in atol (__nptr=0x0) at /usr/include/stdlib.h:285
#3  parse_parameter (ctx_p=ctx_p@entry=0x807e408, param_id=param_id@entry=114, arg=0x0, paramsource=paramsource@entry=PS_ARGUMENT) at main.c:1236
#4  0x08050e17 in arguments_parse (argc=10, argv=0xbfffd6e4, ctx_p=ctx_p@entry=0x807e408) at main.c:1656
#5  0x0804cb4e in main (_argc=10, _argv=0xbfffd6e4) at main.c:2324
(gdb)

**Comment by bircoph** [comment]
Fixed in 51affaa
